### ISSUE TITLE
i can't stitch more than 2 pictures 

### ISSUE THREAD

**Issue by mangel1196** [josundin/josundin.github.io#1]
when i try to stitch 3 or more pictures the library just found coincidences with the first and the second,

the pictures was taken like a panoramic, one at the right of the other.

please help me,

thanks for your atention

**Comment by josundin** [comment]
Hello.
There is a limitation of what it can stitch together, dependent on the matching algorithm and the ORB Descriptors.

The program doesn't do any check for overlapping parts. So you have do make sure the images get loaded in the correct order. One way to do that is to rename them to e.g 1.jpg, 2.jpg 3.jpg
You can see an example here:
http://josundin.github.io/stitch/demoorb/

The stitching is based on the ORB Descriptors from jsfeat. 
https://inspirit.github.io/jsfeat/#features2d

**Comment by mangel1196** [comment]
Hi, 
Thanks for your answer and the problem is that, the no checking of the overlapping parts, but i resolved replacing the base image for each union.

P.S. 
Sorry for my english, 
Greetings from Colombia
